### ISSUE TITLE
Type mismatch in example usage

### ISSUE THREAD

**Issue by aza547** [sindresorhus/image-dimensions#8]
![image](https://github.com/sindresorhus/image-dimensions/assets/32389325/d76bfc08-52ca-4c2e-bd2e-49b9fcceece8)

Following the example in the README, I get the above warning. 

It seems this is due to createReadStream returning a `ReadStream` while `imageDimensionsFromStream` expects a `ReadableStream<Uint8Array>`.

**Comment by sindresorhus** [comment]
That's a bug in the code examples. See how to fix here: https://github.com/sindresorhus/image-dimensions/commit/c9d959454d93ee51c4527779407c8fe730afc8d3#diff-7aa4473ede4abd9ec099e87fec67fd57afafaf39e05d493ab4533acc38547eb8L29-R29
